<template>
  <div class="mx-auto max-w-3xl space-y-4 px-5 my-10">

    <p class="text-sky-600 text-xs">Independent Development: The Future of Software</p>
    <p class="text-3xl font-bold leading-8 tracking-tight text-neutral-600 sm:text-3xl">
      Outside the Walled Garden
    </p>

    <p class="text-lg dark:text-neutral-400 text-neutral-600">
      The rise of mobile applications and the increasing popularity of smartphones and tablets
      have given rise to two major app stores, the Apple App Store and Google Play Store.
      These app stores have become gatekeepers, controlling which applications are allowed onto mobile devices,
      and which are not. While this approach may seem like a way to ensure security and quality control,
      it has also created a walled garden that is stifling innovation and competition.
    </p>

    <LilSpacer />

    <h4 class="text-lg font-semibold text-sky-600">The Walled Garden Problem</h4>
    <p>
      The main problem with the app store model is the lack of freedom it provides developers.
      App store guidelines are often very restrictive, and developers must comply with them if
      they want their apps to be approved. This can stifle innovation and creativity, as developers
      are limited in what they can do with their apps.
    </p>
    <p>
      Add that to the fact that app stores often charge developers a fee for listing their apps on the store,
      and they take a percentage of any revenue generated by the app. This can make it difficult for smaller
      developers to make a profit, as they are effectively giving away a portion of their earnings to the app
      store.
    </p>
    <h4 class="font-bold text-lg dark:text-neutral-300 text-neutral-700 pt-10">
      Here are some of the benefits of independent development:
    </h4>
    <ul class="p-5 m-5 pb-10 list-disc marker:text-sky-600/50">
      <li class="font-bold p-1">
        More control for developers: Developers have more control over their apps when they distribute them directly to
        users. They can set their own prices, update their apps more frequently, and reach a wider audience.
      </li>
      <li class="font-bold p-1">
        More choice for users: Users have more choice when they can install apps from outside of the app stores. They can
        find apps that are not available on the app stores, and they can choose to support developers who are not part of
        the big tech companies.
      </li>
      <li class="font-bold p-1">
        A more diverse and innovative app ecosystem: Independent development helps to keep the app ecosystem more diverse
        and innovative. When developers are not beholden to the app stores, they are more likely to take risks and try new
        things. This leads to a wider variety of apps being available to users.
      </li>
    </ul>

    <p>Independent development is also better for users. It gives users more choice and allows them to find apps that are
      not available on the app stores. It also helps to keep the app ecosystem more diverse and innovative.</p>
    <p>Independent development allows developers to distribute their apps directly to users, without having to go through
      Apple or Google. This gives developers more control over their apps and allows them to reach a wider audience.</p>
    <p> Another benefit of independent development is the potential for more competition. With more developers able to
      create and distribute their apps, consumers have a wider range of options to choose from. This can lead to more
      competition and ultimately better products for consumers.</p>
    <h4 class="font-bold text-lg dark:text-neutral-300 text-neutral-700 pt-10"> Support Independent Development</h4>
    <p>Independent development outside of app store walled gardens is better than relying on two corporations to decide
      what software gets into the masses' hands. The app store model may have been necessary in the early days of mobile
      app development, but it has become a barrier to innovation and competition.</p>
    <p> Independent development allows for more creativity and competition, and it gives developers the freedom to create
      the apps they want without having to comply with restrictive guidelines. As consumers, we should support independent
      developers and seek out their apps whenever possible.</p>

  </div>
</template>

<script setup>
import LilSpacer from '../shared/LilSpacer.vue';
import { ref } from 'vue';
const content = ref(
  [
    'https://imagedelivery.net/jUv0WjkQAcJxE0kRYIap3Q/bb412629-6cff-4e5c-f658-69b49d238300/public',
    'Outside of the Walled Garden',
    'Independent Development: The Future of Software'
  ]
)
</script>